---
name: CI/CD Pipeline for Ansible Playbooks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Ansible Playbooks
        uses: ansible/ansible-lint-action@v4
  run_playbooks:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Ansible
        run: pip install ansible
      - name: Run Ansible Playbooks
        run: ansible-playbook -i ansible/hosts.ini ansible/playbook.yml
